homepage: "https://github.com/Misat0N/inih"
language: c
primary_contact: "articussnagato@gmail.com"
auto_ccs:
  - "pkillarjun@protonmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/Misat0N/inih'
